# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      environment:
        description: "Enter Yes"
        type: string
        required: True
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  comment-job:
    runs-on: ubuntu-latest
  # This workflow contains a single job called "build"
  # build:
  #   # The type of runner that the job will run on
  #   runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - name: Checkout Repository
      #   uses: actions/checkout@v4

      # # Runs a single command using the runners shell
      # - name: Run a one-line script
      #   run: echo ${{inputs.environment}}
      #       echo ${{github.actor}}
        
      # - name: GITHUB API with PAT
      #   env:
      #     GITHUB_TOKEN: ${{secrets.GITHUBTRAINING}}
      #   run: |
      #       curl -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/user
          
      # # Runs a set of commands using the runners shell
      # - name: Make Changes
      #   run: |
      #     git config --global user.email "parmarnirav600@gmail.com"
      #     git config --global user.name "Nirav0702"

      #     echo "New Changes" >> changes.txt
      #     git add changes.txt
      #     git commit -m "Add Changes"

      # - name: Push changes
      #   env:
      #       GITHUB_TOKEN: ${{secrets.GITHUBTRAINING}}
      #   run: |
      #     git push origin feature_branch

      # - name: Comment on Pull Request
      #   env:
      #     GITHUB_TOKEN: ${{secrets.GITHUBTRAINING}}
      #   run: |
      #     PR_NUMBER=${{ github.event.pull_request.number }}
      #     curl -X POST -H “Authorization: token $GITHUB_TOKEN” \
      #     -d '{"body": "Thanks you for your contribution"}' \
      #     https://api.github.com/repos/Nirav0702/Github-Training/issues/$PR_NUMBER/comments

      - name: Checkout this repo
        uses: actions/checkout@v2

      - name: Checkout another repo
        uses: actions/checkout@v2
        with:
          repository: Nirav0702/Github-Training
          token: ${{secrets.GITHUBTRAINING}}
          path: other-repo

      - name: Set up Python
        uses: actions/setup-python@v2
        with: 
          python-version: '3.x'

      - name: Run Python script
        run: |
          cd other-repo
          python script.py
